##########################################
#
# merged_beam_read.yaml
#
# Configuration for tracking extra beam 
# receivers' raw data file reading
#
# Author: Jing Luo
#
##########################################
---
type: config
log_level: debug2
cpu_affinity: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
samples_per_data_set: 49152
num_pol: 2
buffer_depth: 105
raw_frames_per_merged_frame: 6
# The size of metadata with freq ID
freq_id_metadata_size: 72

telescope:
  name: CHIMETelescope
  require_gps: true
  query_gps: true
  require_frequency_map: true
  query_frequency_map: true
  allow_default_frequency_map: false

dataset_manager:
  use_dataset_broker: false

beam_metadata_pool:
  kotekan_metadata_pool: BeamMetadata
  num_metadata_objects: 4096

frame_merged_buffer:
  kotekan_buffer: standard
  num_frames: 2048
  metadata_pool: beam_metadata_pool
  frame_size: samples_per_data_set * num_pol

beam_raw_buffer:
  kotekan_buffer: standard
  num_frames: 2048
  metadata_pool: beam_metadata_pool
  frame_size: samples_per_data_set * num_pol

merged_raw_file_read:
  base_dir: /drives/scratch/test_beam_raw
  file_name: bass_merged_beam_data
  read0:
    kotekan_stage: mergedRawFileRead
    file_ext: raw
    merged_buf: frame_merged_buffer
    out_buf: beam_raw_buffer
